[package]
name = "day_03a_loader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uefi = { version = "0.16.0", features = ["exts", "alloc"] }
uefi-services = "0.13.0"
